### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by MikeVL** [gsterjov/angular-tasty-resource#1]
This is my test script:

```
angular.module('offersAdmin').factory('Offer', ['TastyResource', function (TastyResource) {
        return TastyResource({
            url: 'http://127.0.0.1:8001/market/api/v1/offer/'
        });
}]);

angular.module('offersAdmin').controller('IndexCtrl', [
    '$scope', '$routeParams', 'Rubrica', function ($scope, $routeParams, Rubrica) {
        $scope.rubricaID = $routeParams.rubricaID || null;

        var rubrica = Rubrica.get($scope.rubricaID);

        console.log('Rubrica:', rubrica);
        console.log('id:', rubrica.id);
        console.log('title:', rubrica.title);
    }
]);
```

Console output:

```
Rubrica: TastyResourceFactory
id: undefined
title: undefined
```

Why object attributes undefined in controller?

![2014-02-10 21 11 47](https://f.cloud.github.com/assets/118285/2128082/79cfe524-9276-11e3-982b-dd139dd49702.jpg)

**Comment by gsterjov** [comment]
All API calls are asynchronous which means that rubrica.id and rubrica.title doesn't exist when printing to console because Rubrica.get hasn't finished retrieving the data yet.

The chrome console updates objects which is why it appears that console.log(rubrica) worked, when in fact it finished afterwards and chrome updated the reference to show the new attributes.

To get the data in the controller you will have to provide a callback for the success callback, similar to angular.$resource

```
var rubrica = Rubrica.get($scope.rubricaID, function(response){
    console.log("id:", rubrica.id);
    console.log("title:", rubrica.title);
});
```

It will work as expected in angular templates, so {{ rubrica.title }} should populate once the data async process has finished.

Feel free to reopen this issue if it's still not working.

**Comment by MikeVL** [comment]
Thanks for the help. This code works fine.

**Comment by audoeyop** [comment]
@gsterjov Can you update the documentation to reflect this, por favor?

**Comment by gsterjov** [comment]
@audoeypop, good idea. Hopefully I'll get some time to do it soon. Otherwise feel free to make a pull request and I'll look it over
