### ISSUE TITLE
Update $scope after put()

### ISSUE THREAD

**Issue by fproldan** [gsterjov/angular-tasty-resource#4]
Hi, i have a resource in my controller and in the template i use ng-repeat:

``` javascript
app.controller('FooCtrl', ["$scope", "Foo",  function($scope, Foo) {
    $scope.foos = Foo.query();

    $scope.change_foo = function(form) {
        ...
        $scope.foo_object.attribute = "change";
        $scope.foo_object.put()
    }
}]);
```

So far, the put() is doing correctly, but the $scope.foos doesn't update. I tried with $scope.$apply() but doesn't work.

How can i reach this goal?

Thank you!

**Comment by gsterjov** [comment]
The resources are pretty blunt. It doesn't try very hard to keep all resources in sync because sometimes you might not want it to be. So it would be entirely up to you to determine how the objects are used.

If foo_object is a reference to the same resource instance in foos then both objects would update. But if you call .query and then .get(id), you will most likely have to refresh the .query results by running it again.

I'll test these scenarios again when I get time so please correct me if is not working as expected
